// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ucminf_cpp
List ucminf_cpp(NumericVector par, Function fn, Function gr, bool has_gr, List control);
RcppExport SEXP _ucminfcpp_ucminf_cpp(SEXP parSEXP, SEXP fnSEXP, SEXP grSEXP, SEXP has_grSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< Function >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< Function >::type gr(grSEXP);
    Rcpp::traits::input_parameter< bool >::type has_gr(has_grSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(ucminf_cpp(par, fn, gr, has_gr, control));
    return rcpp_result_gen;
END_RCPP
}

// ucminf_fdf_cpp
List ucminf_fdf_cpp(NumericVector par, Function fdfun, List control);
RcppExport SEXP _ucminfcpp_ucminf_fdf_cpp(SEXP parSEXP, SEXP fdfunSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< Function >::type fdfun(fdfunSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(ucminf_fdf_cpp(par, fdfun, control));
    return rcpp_result_gen;
END_RCPP
}

// ucminf_xptr_cpp
List ucminf_xptr_cpp(NumericVector par, SEXP xptr, List control);
RcppExport SEXP _ucminfcpp_ucminf_xptr_cpp(SEXP parSEXP, SEXP xptrSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(ucminf_xptr_cpp(par, xptrSEXP, control));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ucminfcpp_ucminf_cpp",      (DL_FUNC) &_ucminfcpp_ucminf_cpp,      5},
    {"_ucminfcpp_ucminf_fdf_cpp",  (DL_FUNC) &_ucminfcpp_ucminf_fdf_cpp,  3},
    {"_ucminfcpp_ucminf_xptr_cpp", (DL_FUNC) &_ucminfcpp_ucminf_xptr_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ucminfcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
