# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Unconstrained Nonlinear Optimization (C/Rcpp implementation)
#'
#' Internal function called by \code{\link{ucminf}}. Use that instead.
#'
#' @param par Numeric vector of starting values.
#' @param fn R function returning the objective value.
#' @param gr R function returning the gradient, or NULL.
#' @param has_gr Logical: TRUE if gr is provided.
#' @param control Named list of control parameters:
#'   \code{grtol}, \code{xtol}, \code{stepmax}, \code{maxeval},
#'   \code{grad}, \code{gradstep}, \code{invhessian_lt}.
#'
#' @return A list with elements \code{par}, \code{value}, \code{convergence},
#'   \code{neval}, \code{maxgradient}, \code{laststep}, \code{stepmax},
#'   and \code{invhessian_lt}.
#'
#' @keywords internal
ucminf_cpp <- function(par, fn, gr, has_gr, control) {
    .Call(`_ucminfcpp_ucminf_cpp`, par, fn, gr, has_gr, control)
}

